export const ICONS = {
    reply: `<img src="./images/svg/reply.svg" class="icon" alt="Reply">`,
    boost: `<img src="./images/svg/boost.svg" class="icon" alt="Boost">`,
    favorite: `<img src="./images/svg/favorite.svg" class="icon" alt="Favorite">`,
    bookmark: `<img src="./images/svg/bookmark.svg" class="icon" alt="Bookmark">`,
    more: `<img src="./images/svg/more.svg" class="icon" alt="More options">`,
    notifications: `<img src="./images/svg/notifications.svg" class="icon" alt="Notifications">`,
    refresh: `<img src="./images/svg/refresh-spinner.svg" class="icon" alt="Refresh">`,
    edit: `<img src="./images/svg/edit.svg" class="icon" alt="Edit">`,
    delete: `<img src="./images/svg/delete.svg" class="icon" alt="Delete">`,
    mention: `<img src="./images/svg/mention.svg" class="icon" alt="Mention">`,
    comments: `<img src="./images/svg/comment.svg" class="icon" alt="Comments">`,
    save: `<img src="./images/svg/save.svg" class="icon" alt="Save">`,
    lemmy: `<img src="./images/svg/lemmy.svg" class="icon" alt="Lemmy">`,
    lemmyUpvote: `<img src="./images/svg/upvote.svg" class="icon" alt="Upvote">`,
    lemmyDownvote: `<img src="./images/svg/downvote.svg" class="icon" alt="Downvote">`,
    mastodon: `<img src="./images/svg/mastodon.svg" class="icon" alt="Mastodon">`,
    screenshot: `<img src="./images/svg/screenshot.svg" class="icon" alt="Screenshot">`,
    watermark: `<img src="./images/svg/watermark.svg" class="icon" alt="Feeds">`,
    media: `<img src="./images/svg/media.svg" class="icon" alt="Add media">`,
    poll: `<img src="./images/svg/poll.svg" class="icon" alt="Add poll">`,
    warning: `<img src="./images/svg/warning.svg" class="icon" alt="Add content warning">`
};
